// Code generated by sqlc. DO NOT EDIT.
// source: bookAuthor.sql

package db

import (
	"context"
	"database/sql"
)

const linkBookAuthor = `-- name: LinkBookAuthor :one
INSERT INTO book_authors (
   "book_id",
    "author_id"
) VALUES (
    $1,
    $2
) RETURNING book_author_id, book_id, author_id
`

type LinkBookAuthorParams struct {
	BookID   sql.NullInt32 `json:"book_id"`
	AuthorID sql.NullInt32 `json:"author_id"`
}

func (q *Queries) LinkBookAuthor(ctx context.Context, arg LinkBookAuthorParams) (BookAuthor, error) {
	row := q.db.QueryRowContext(ctx, linkBookAuthor, arg.BookID, arg.AuthorID)
	var i BookAuthor
	err := row.Scan(&i.BookAuthorID, &i.BookID, &i.AuthorID)
	return i, err
}
