// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Author struct {
	AuthorID  int64  `json:"author_id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

type Book struct {
	BookID          int64          `json:"book_id"`
	Title           string         `json:"title"`
	Isbn            string         `json:"isbn"`
	PublicationYear sql.NullInt32  `json:"publication_year"`
	AuthorID        sql.NullInt32  `json:"author_id"`
	PublisherID     sql.NullInt32  `json:"publisher_id"`
	GenreID         sql.NullInt32  `json:"genre_id"`
	Price           sql.NullString `json:"price"`
	StockQuantity   sql.NullInt32  `json:"stock_quantity"`
}

type BookAuthor struct {
	BookAuthorID int64         `json:"book_author_id"`
	BookID       sql.NullInt32 `json:"book_id"`
	AuthorID     sql.NullInt32 `json:"author_id"`
}

type Genre struct {
	GenreID   int64  `json:"genre_id"`
	GenreName string `json:"genre_name"`
}

type Publisher struct {
	PublisherID   int64          `json:"publisher_id"`
	PublisherName string         `json:"publisher_name"`
	Address       sql.NullString `json:"address"`
	Phone         sql.NullString `json:"phone"`
}
